### PR TITLE
Minimal implementation of artifact pages

### PR DESCRIPTION
**Pull request by vossad01**
This provides artifacts their own page resolving some abstraction issues with displaying artifact information on the project page.

This is not perfect in that there are a lot of additional things that I can think of that someone might iterated on top of this, but I do not believe it regresses and it takes care of all the hard (busy) work of providing the two different types of pages.

**Example Project Page:**
screen shot 2017-01-04 at 16 06 05-fullpage

**Example Artifact Page:**
screen shot 2017-01-04 at 16 11 23-fullpage

### This partially addresses:
 - [Display which targets are library supports, #288](https://github.com/scalacenter/scaladex/issues/288): Provides information without graphical logos; no front-page or search results modifications.

### This obsoletes:
 - #320
 - #317
 - #313

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
really cool, I like the simplification of the ui. Lets talk more about this on gitter:
https://gitter.im/scalacenter/scaladex

**Comment by vossad01** [comment]
[Discusson on gitter starts here](https://gitter.im/scalacenter/scaladex?at=586e5796db9cafe9183b7c8a).

Main concern raised was that this introduces an "extra click" to get from the project page to information about an artifact.  #326 was created as a result.

**Comment by vossad01** [comment]
I have pushed additional commits that attempt to mitigate the "extra click" problem.  
This does not implement #326 for reasons listed on that item.

screen shot 2017-01-07 at 23 00 57-fullpage

**Comment by MasseGuillaume** [comment]
Really good! and x More solves the too much artifacts problems.

**Comment by vossad01** [comment]
Was something more needing to be done regarding this Pull Request?

I am weighing whether I should rebase it again.

**Comment by MasseGuillaume** [comment]
Hey, sorry I forgot your PR. This is great work. Let met do the rebase for you.

**Comment by vossad01** [comment]
Thanks!  Normally I would take you up on that (esp, since I  encounter minor issues when I last tried  :smile:), but I also have another commit locally that fixes a minor bug in this (caused user to see a server error page instead of 404 when trying to access bogus project), so I feel it is somewhat my responsibility to do the rebase so I can squash that commit in.

**Comment by MasseGuillaume** [comment]
@vossad01 you can create annother PR for the bugfix ;-)

**Comment by vossad01** [comment]
Thank you :)

**Comment by MasseGuillaume** [comment]
rebased PR: https://github.com/scalacenter/scaladex/pull/340

**Comment by heathermiller** [comment]
The UI has become very confusing now as a result of this change. I understand arguments for, but I think that as implemented so far this greatly hurts usability.

**Comment by heathermiller** [comment]
It took me minutes of browsing around to figure out what happened, what version of the libraries I was on, before I even realized that there was a new artifacts pane. Now I don't know how to switch target versions. I had to browse the issue tracker before realizing that this functionality had been removed without replacement.

**Comment by heathermiller** [comment]
As far as I see it, we lost functionality by merging this change. Sure, I understand that there's another ticket open now and that this is essentially a work in progress, but a lot of people use Scaladex everyday. We can't go days or weeks dropping depended-on functionality when people depend on this tool. I suggest we revert until all functionality is back.

**Pull request closed without merging**
