### PR TITLE
Allow indexing non-standard java projects #302

### PR DESCRIPTION
**Pull request by ktoso**
Thanks for the hints #302, they made it pretty simple to jump in and implement it.

I'm not sure where I should add a test covering this though, any hints?
Is the existing logic for that tested somewhere (could not find one but maybe I'm blind - sorry if so).

Aims to resolve https://github.com/scalacenter/scaladex/issues/302

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
:sparkler: amazing we don't have a nice test suite for this yet. Let met test manually ;-).

**Comment by ktoso** [comment]
Ok, thanks :) Hope it's all there was to fix.

**Comment by MasseGuillaume** [comment]
@ktoso thanks a lot, I'm merging your commit here: https://github.com/scalacenter/scaladex/pull/306/commits

**Comment by ktoso** [comment]
Awesome, glad I could help :) thanks.

-- 
Konrad Malawski

**Pull request closed without merging**
