### PR TITLE
fix #636: add version matrix button

### LINKED ISSUE #636: Add a compatibility grid button in the project page
In a project page, for instance https://index.scala-lang.org/typelevel/cats, add a button to go to the compatibility grid page of the project https://index.scala-lang.org/artifacts/typelevel/cats.

In the compatibility grid page add a button to go back to the project page.

### PR DESCRIPTION
**Pull request by bishabosha**
Screenshot 2020-11-10 at 16 08 14

### CODE REVIEW

**Comment by vincenzobaz** [comment]
There is a typo in the label name (*Compatibility*).
Maybe we can find a more appropriate name too.
What about **Version grid** ?

**Review by adpi2 — CHANGES_REQUESTED** [review]
`scalafmt` in travis CI is complaining...

Can you run `bin/scalafmt` and push again?

Thx

**Comment by tgodzik** [comment]
> `scalafmt` in travis CI is complaining...
> 
> Can you run `bin/scalafmt` and push again?
> 
> Thx

scalafmt seems to be broken. It's not really possible to run it locally :/ 

I updated it in the actions PR

**Comment by adpi2** [comment]
You are right @tgodzik. 
So we'll merge #642 first then rebase and it should fix the issue with `scalafmt`.

**Comment by bishabosha** [comment]
I've rebased

**Review by adpi2 — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
