### PR TITLE
Updated sbt-bintray link

### PR DESCRIPTION
**Pull request by laughedelic**
Also added a link to publishing docs

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
Merci!

**Comment by laughedelic** [comment]
You already have FAQ in the wiki. How about moving these docs to wiki as well? I think it makes little fixes like this one much easier for users/contributors.

**Comment by MasseGuillaume** [comment]
Yep this would be useful too https://github.com/scalacenter/scaladex/wiki/FAQ

The advantage of the README is that it's the first thing you look at. If the information is not there most of the user would give up at this point.

**Comment by laughedelic** [comment]
I agree about readme (which should mention wiki). I meant moving docs in `doc/user/` to wiki.

**Pull request merged**
