### PR TITLE
Add link to blog post in banner

### PR DESCRIPTION
**Pull request by MichaelViveros**
@heathermiller Added link to Contributing Info blog post (section about How to Add Your Project) in the front page banner

Also ran scalafmt

### CODE REVIEW

**Comment by heathermiller** [comment]
The link fix definitely looks good to me. 

Since @MasseGuillaume is in charge of this repo, I'll let him make the call on the stylistic changes.

**Comment by MasseGuillaume** [comment]
Thanks!

I'm not super picky about commits, but it should really just include this in the diff: https://github.com/scalacenter/scaladex/pull/495/files#diff-b122b302abeb18b749ca2ee96f9a4ff9R51

**Comment by MichaelViveros** [comment]
Agreed. I'll make sure to run `scalafmt` as a separate commit in the future.

**Comment by MichaelViveros** [comment]
Also, @MasseGuillaume please let me know when it's deployed

**Comment by MichaelViveros** [comment]
@MasseGuillaume Did you get a chance to deploy this yet?

**Comment by heathermiller** [comment]
Thanks for the ping, @MichaelViveros. @MasseGuillaume can we get this deployed?

**Comment by MasseGuillaume** [comment]
Deploying now.

You guys also have all the access to deploy: https://github.com/scalacenter/scaladex/blob/master/CONTRIBUTING.md#how-to-deploy

**Comment by MasseGuillaume** [comment]
Now live: https://index.scala-lang.org/

**Pull request merged**
