### PR TITLE
Add support for navigation in the autocompletion list using keys

### PR DESCRIPTION
**Pull request by julienrf**
Hi,

I’ve just added support for navigating in the autocompletion list using the keyboard arrows (and pressing Enter shows the details of the project).

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
add to whitelist

**Comment by MasseGuillaume** [comment]
fix #219

**Comment by MasseGuillaume** [comment]
@julienrf ty !

above some jenkins command to ignore :P
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by heathermiller** [comment]
!! 🎉 🍻 👯 👍 
Thank you @julienrf!!

**Pull request merged**
