### PR TITLE
Reverse sort stats on project pages

### PR DESCRIPTION
**Pull request by adpi2**
As a follow up of #1153

In the project header:
image

In the project's list of artifacts:
image

### CODE REVIEW

**Comment by adpi2** [comment]
And it's live: https://index.scala-lang.org/

**Comment by scalway** [comment]
styles are wrong!

**Comment by adpi2** [comment]
@scalway Thanks for reporting, I am redeploying now.

**Comment by adpi2** [comment]
Should be working now

**Pull request merged**
