### PR TITLE
 fix #92 - add theme color for android

### LINKED ISSUE #92: theme color for android
https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/theme-color?hl=en

### PR DESCRIPTION
**Pull request by Scyks**

### CODE REVIEW

**Comment by heathermiller** [comment]
🎉 🍺 👏 :)

**Comment by heathermiller** [comment]
Hey look @nicholasstucki & @jvican! :) 
Thank you @Scyks! A group of us was chatting over dinner at Scala Days, speculating whether it was meta tags or something else that we had to use to change this. Will try it out when I'm at a computer, thanks!

**Comment by Scyks** [comment]
I just checked it in the iPhone Simulator. This works fine. For Android i can't tell you. The simulators sucks. Hope that's what you expected :)

**Comment by jvican** [comment]
This is great! :wink:

**Pull request merged**
