### PR TITLE
Fix type in example

### PR DESCRIPTION
**Pull request by lunaryorn**
"credentials" is a list; we need += to add a value.

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
Thanks

**Comment by lunaryorn** [comment]
@MasseGuillaume You're welcome, thanks for merging so fast.

By the way, do you happen to know why the document scopes `credentials` in `Scaladex`?  Does that make a difference?

Like most people I already got a global `credentials.sbt` with my Sonatype credentials; adding my Scaladex credentials globally would require me to install the plugin globally to have the Scaladex scope available.  Since I don't want to do that I've added the credentials without the scope restrictions, and things still seem to work well, so I'm left quite confused 😕 :blush:

**Comment by MasseGuillaume** [comment]
Hum, it should be scoped: https://github.com/scalacenter/scaladex/blob/master/sbtScaladex/src/main/scala/org.scala_lang.index.sbt/ScaladexPlugin.scala#L41

I'm not sure why it works.

**Comment by lunaryorn** [comment]
@MasseGuillaume Well, according to `inspect actual scaladex:credentials` it depends (i.e. delegates?) to `*:credentials`, i.e. what I change with `credentials += …` in a global `credentials.sbt`.

That's why it works, but I wonder whether that's intentional, given that the documentation makes the scope explicit.

**Pull request merged**
